### ISSUE TITLE
The different between numpy function and ndarray method

### ISSUE THREAD

**Issue by Xls1994** [Kyubyong/numpy_exercises#5]
Hi, I have a small confused  with numpy.
For example, we can use the numpy.reshape(x,(1,3)) to reshape a array. Also we can use x.reshape((1,3)) to do this. What is the major difference between the two ? Thank you !

**Comment by Kyubyong** [comment]
I think both are identical.

**Comment by Xls1994** [comment]
Thanks for your answer!
